### ISSUE TITLE
集成 Wechaty Chatopera Plugin

### ISSUE THREAD

**Issue by hailiang-wang** [chatopera/osschat#2]
使用 https://github.com/wechaty/wechaty-chatopera

通过配置环境变量，读取是否配置了 Chatopera 机器人。
比如

```
CHATOPERA_CLIENT_ID
CHATOPERA_SECRET
CHATOPERA_PROVIDER=https://bot.chatopera.com  # 默认
CHATOPERA_FAQ_BEST_REPLY=0.9   # 默认，知识库回答阈值
```

如果配置了 `CHATOPERA_CLIENT_ID` 和 `CHATOPERA_SECRET` 则在 Wechaty use 中添加 chatopera plugin。

1. 收集对话 - 群聊和私聊都映射为一个用户，在 Chatopera 聊天机器人管理控制台可以看到对话。
2. 使用 `conversation/query` 做多轮对话检索，并指定 faqBestReplyThreshold 为 设置值。

当机器人能回答问题，直接发群里。

在群里，有意图识别对话时，如不同用户进行对话，都按同一用户对话进行处理。

比如：A 群里 B 说：我要点餐，机器人识别到意图，问“您要吃什么”，这时候 C 说 - “麻婆豆腐”，机器人说”好的，下单了“。

**Comment by hailiang-wang** [comment]
Related with https://github.com/kaiyuanshe/osschat/issues/152

**Comment by mukaiu** [comment]
环境变量

```
WECHATY_PLUGIN_CHATOPERA_CLIENTID
WECHATY_PLUGIN_CHATOPERA_SECRET
WECHATY_PLUGIN_CHATOPERA_BESTSCORE_THRESHOLD
WECHATY_PLUGIN_CHATOPERA_SUGGSCORE_THRESHOLD
```

**Comment by hailiang-wang** [comment]
> 环境变量
> 
> ```
> WECHATY_PLUGIN_CHATOPERA_CLIENTID
> WECHATY_PLUGIN_CHATOPERA_SECRET
> WECHATY_PLUGIN_CHATOPERA_BESTSCORE_THRESHOLD
> WECHATY_PLUGIN_CHATOPERA_SUGGSCORE_THRESHOLD
> ```

环境变量太长了，建议优化为：

```
CHATOPERA_CLIENTID
CHATOPERA_SECRET
CHATOPERA_BEST_REPLY_THRES
CHATOPERA_SUGG_REPLY_THRES
```
